accounts/urls.py
from django.urls import path
from .views import *
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', signup_view, name='signup_view'),
    path('logout/', logout_view, name='logout_view'),
    path('login/', login_view, name='login_view'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'), name='index'),
    path('employer/', include('employer.urls')),
    path('employee/', include('employee.urls')),
    path('managing/', include('managing.urls')),
    path('mypage/', include('mypage.urls')),
    path('accounts/', include('accounts.urls')),
]

employee/urls.py
from django.urls import path
from .views import *

app_name = 'employee'

urlpatterns = [
    path('',employee_all, name='employee_all'),
    path('new/',new_feed, name='new_feed'),
    path('feed/<pk>/', detail_feed),
    path('feed/<pk>/remove/', remove_feed),
    path('feed/<pk>/edit/', edit_feed),
]

employer/urls.py
from django.urls import path

from .views import *

app_name = 'employer'

urlpatterns = [
    path('', employer_all, name='employer_all'),
]

main/urls.py
from django.urls import path

from .views import *

app_name = 'main'

urlpatterns = [
    path('', index, name='index'),
]

mypage/urls.py
from django.urls import path

from .views import *

app_name = 'mypage'

urlpatterns = [
    path('', mypage_detail, name='mypage_detail'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required Meta Tags -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!-- Page Title -->
    <title>{% block title %}{%endblock%}</title>

    <!-- Favicon -->
    <link rel="shortcut icon" href="assets/images/logo/favicon.png" type="image/x-icon">

    {% load static %}
    <!-- CSS Files -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/animate-3.7.0.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-4.1.3.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/owl-carousel.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/nice-select.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/menubar.css' %}">
</head>
<body>
    <!-- Preloader Starts -->
    <div class="preloader">
        <div class="spinner"></div>
    </div>
    <!-- Preloader End -->

    <!-- Header Area Starts -->
	<header class="header-area main-header">
        <div class="container">
            <div class="row">
                <div class="col-lg-2">
                    <div class="logo-area">
                        <a href="{% url 'main:index' %}" class=inkfont><!--
                            <img src="{% static 'image/logo.png'%}" alt="logo">
                        -->
                            Heros
                        </a>
                    </div>
                </div>
                <div class="col-lg-10">
                    <div class="custom-navbar">
                        <span></span>
                        <span></span>
                        <span></span>
                    </div>
                    <div class="main-menu" class=inkfont>
                        <ul>
                            <li><a href="{% url 'employer:employer_all' %}">구인</a></li>
                            <li><a href="{% url 'employee:employee_all' %}">구직</a></li>
                            <li><a href="{% url 'managing:Notice_all' %}">고객센터</a>
                                <ul class="sub-menu">
                                    <li><a href="{% url 'managing:Notice_all' %}">공지사항</a></li>
                                    <li><a href="{% url 'managing:FAQ_all' %}">FAQ</a></li>
                                </ul>
                            </li>
                            <li class="menu-btn">
                                {% if user.is_authenticated %}
                                <li><a href="{% url 'mypage:mypage_detail' %}">마이페이지</a></li>
                                <li><a href="{%url 'accounts:logout_view'%}">로그아웃</a></li>
                                {%else%}
                                <a href="{%url 'accounts:login_view'%}" class="login">로그인</a>
                                <a href="{%url 'accounts:signup_view'%}" class="template-btn">회원가입</a>
                                {%endif%}
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!-- Header Area End -->
    {% block contents %}
    {% endblock %}
    <!-- Footer Area Starts -->
    <footer class="footer-area" style="padding:10px">
            <div class="footer-copyright">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-8 col-md-6">
                            <span>
<<<<<<< HEAD
=======
                                Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib
>>>>>>> upstream/master
                                <br> 2020 Software Engineering 윤동준 이준병 이상목 이진우 박재성</a>
                                </span>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Footer Area End -->
    <!-- Javascript -->
    <script src="{% static 'js/vendor/jquery-2.2.4.min.js'%}"></script>
	<script src="{% static 'js/vendor/bootstrap-4.1.3.min.js'%}"></script>
    <script src="{% static 'js/vendor/wow.min.js'%}"></script>
    <script src="{% static 'js/vendor/owl-carousel.min.js'%}"></script>
    <script src="{% static 'js/vendor/jquery.nice-select.min.js'%}"></script>
    <script src="{% static 'js/vendor/ion.rangeSlider.js'%}"></script>
    <script src="{% static 'js/main.js'%}"></script>
</body>
</html>